// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen_deps.go; DO NOT EDIT.

package integration

import (
	// And depend on a bunch of tailscaled innards, for Go's test caching.
	// Otherwise cmd/go never sees that we depend on these packages'
	// transitive deps when we run "go install tailscaled" in a child
	// process and can cache a prior success when a dependency changes.
	_ "github.com/dblohm7/wingoes/com"
	_ "github.com/tailscale/wireguard-go/tun"
	_ "golang.org/x/sys/windows"
	_ "golang.org/x/sys/windows/svc"
	_ "golang.org/x/sys/windows/svc/eventlog"
	_ "golang.org/x/sys/windows/svc/mgr"
	_ "golang.zx2c4.com/wintun"
	_ "golang.zx2c4.com/wireguard/windows/tunnel/winipcfg"
	_ "github.com/Jnchk/tailscale/cmd/tailscaled/childproc"
	_ "github.com/Jnchk/tailscale/control/controlclient"
	_ "github.com/Jnchk/tailscale/derp/derphttp"
	_ "github.com/Jnchk/tailscale/envknob"
	_ "github.com/Jnchk/tailscale/ipn"
	_ "github.com/Jnchk/tailscale/ipn/ipnlocal"
	_ "github.com/Jnchk/tailscale/ipn/ipnserver"
	_ "github.com/Jnchk/tailscale/ipn/store"
	_ "github.com/Jnchk/tailscale/logpolicy"
	_ "github.com/Jnchk/tailscale/logtail"
	_ "github.com/Jnchk/tailscale/logtail/backoff"
	_ "github.com/Jnchk/tailscale/net/dns"
	_ "github.com/Jnchk/tailscale/net/dnsfallback"
	_ "github.com/Jnchk/tailscale/net/interfaces"
	_ "github.com/Jnchk/tailscale/net/netmon"
	_ "github.com/Jnchk/tailscale/net/netns"
	_ "github.com/Jnchk/tailscale/net/proxymux"
	_ "github.com/Jnchk/tailscale/net/socks5"
	_ "github.com/Jnchk/tailscale/net/tsdial"
	_ "github.com/Jnchk/tailscale/net/tshttpproxy"
	_ "github.com/Jnchk/tailscale/net/tstun"
	_ "github.com/Jnchk/tailscale/paths"
	_ "github.com/Jnchk/tailscale/safesocket"
	_ "github.com/Jnchk/tailscale/smallzstd"
	_ "github.com/Jnchk/tailscale/syncs"
	_ "github.com/Jnchk/tailscale/tailcfg"
	_ "github.com/Jnchk/tailscale/tsd"
	_ "github.com/Jnchk/tailscale/tsweb/varz"
	_ "github.com/Jnchk/tailscale/types/flagtype"
	_ "github.com/Jnchk/tailscale/types/key"
	_ "github.com/Jnchk/tailscale/types/logger"
	_ "github.com/Jnchk/tailscale/types/logid"
	_ "github.com/Jnchk/tailscale/util/clientmetric"
	_ "github.com/Jnchk/tailscale/util/multierr"
	_ "github.com/Jnchk/tailscale/util/osshare"
	_ "github.com/Jnchk/tailscale/util/winutil"
	_ "github.com/Jnchk/tailscale/version"
	_ "github.com/Jnchk/tailscale/version/distro"
	_ "github.com/Jnchk/tailscale/wf"
	_ "github.com/Jnchk/tailscale/wgengine"
	_ "github.com/Jnchk/tailscale/wgengine/netstack"
	_ "github.com/Jnchk/tailscale/wgengine/router"
)
