// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Package iosdeps is a just a list of the packages we import on iOS, to let us
// test that our transitive closure of dependencies on iOS doesn't accidentally
// grow too large, as we've historically been memory constrained there.
package iosdeps

import (
	_ "bufio"
	_ "bytes"
	_ "context"
	_ "crypto/rand"
	_ "crypto/sha256"
	_ "encoding/json"
	_ "errors"
	_ "fmt"
	_ "io"
	_ "io/fs"
	_ "io/ioutil"
	_ "log"
	_ "math"
	_ "net"
	_ "net/http"
	_ "os"
	_ "os/signal"
	_ "path/filepath"
	_ "runtime"
	_ "runtime/debug"
	_ "strings"
	_ "sync"
	_ "sync/atomic"
	_ "syscall"
	_ "time"
	_ "unsafe"

	_ "github.com/tailscale/wireguard-go/device"
	_ "github.com/tailscale/wireguard-go/tun"
	_ "go4.org/mem"
	_ "golang.org/x/sys/unix"
	_ "github.com/Jnchk/tailscale/hostinfo"
	_ "github.com/Jnchk/tailscale/ipn"
	_ "github.com/Jnchk/tailscale/ipn/ipnlocal"
	_ "github.com/Jnchk/tailscale/ipn/localapi"
	_ "github.com/Jnchk/tailscale/log/logheap"
	_ "github.com/Jnchk/tailscale/logtail"
	_ "github.com/Jnchk/tailscale/logtail/filch"
	_ "github.com/Jnchk/tailscale/net/dns"
	_ "github.com/Jnchk/tailscale/net/netaddr"
	_ "github.com/Jnchk/tailscale/net/tsdial"
	_ "github.com/Jnchk/tailscale/net/tstun"
	_ "github.com/Jnchk/tailscale/paths"
	_ "github.com/Jnchk/tailscale/tempfork/pprof"
	_ "github.com/Jnchk/tailscale/types/empty"
	_ "github.com/Jnchk/tailscale/types/logger"
	_ "github.com/Jnchk/tailscale/util/clientmetric"
	_ "github.com/Jnchk/tailscale/util/dnsname"
	_ "github.com/Jnchk/tailscale/version"
	_ "github.com/Jnchk/tailscale/wgengine"
	_ "github.com/Jnchk/tailscale/wgengine/router"
)
